dist: xenial
addons:
  chrome: stable
  firefox: latest
branches:
  only:
  - master
language: node_js
node_js: lts/*
env:
- MOZ_HEADLESS=1
install:
- npm install
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      script: npm run test
