dist: xenial
branches:
  only:
  - master
language: node_js
node_js: lts/*
cache: npm
env:
- MOZ_HEADLESS=1
install:
- npm install
jobs:
  include:
    - stage: lint
      script: npm run lint
    - stage: build
      script: npm run build
    - stage: test
      addons:
        chrome: stable
        firefox: latest
      script: npm run test
